name: Bump version
on:
  push:
    branches:
      - main
jobs:
  bump-tag-version:
    runs-on: ubuntu-latest
    concurrency:
      cancel-in-progress: true
      group: semver-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        id: tag_version
        uses: masgeek/github-tag-action@release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""
          create_annotated_tag: true

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Version ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          allowUpdates: true
          makeLatest: true
